import { Nav, Footer1 } from './components/nav'
import 'bootstrap/dist/css/bootstrap.css'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './components/NewFooter'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const inter = Inter({ subsets: ['latin'] })
export default function RootLayout({ children }) {
  return (
      <html lang="en">
          <body className={`${inter.className} container`}>
              <Nav />
              
              <main >
                  {children}
              </main>

              <Footer />
          </body>
    </html>
  )
}
